# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Dossiers d'approfondissement
email:
description: >- # this means to ignore newlines until "baseurl:"
  Une sélection de textes classés par thématiques
twitter_username: Cedric_Eyssette
github_username: eyssette
minimal_mistakes_skin: dark
search: true
locale: fr


# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Cédric Eyssette"
  avatar : "/assets/images/avatar.jpg"
  bio    : "Une sélection de textes classés par thématiques"
  home : "./" 
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://eyssette.github.io/blog"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://www.facebook.com/cedric.eyssette"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/Cedric_Eyssette"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/eyssette"

footer:
  links:

defaults:
  - scope:
      path: ""
    values:
      layout: single
      author_profile: true
      share: false
      comments: false
      related: false
      read_time: true
      classes: wide
  # _posts
  - scope:
      type: posts
    values:
      layout: posts
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: posts


category_archive:
  type: liquid
  path: /auteurs/
  read_time: true
tag_archive:
  type: liquid
  path: /notions/
  read_time: true


collections_dir: textes

collections:
  ethique_environnementale:
    output: true
    permalink: /:collection/:path/
    title: "Ethique environnementale"
    sort_by: title
  ethique_animale:
    output: true
    permalink: /:collection/:path/
    title: "Ethique animale"
    sort_by: title
  grands_defis_environnementaux:
    output: true
    permalink: /:collection/:path/
    title: "Grands défis environnementaux"
    sort_by: title
  le_temps_est_il_un_obstacle_au_bonheur:
    output: true
    permalink: /:collection/:path/
    title: "Le temps est-il un obstacle au bonheur ?"
    sort_by: title
  philosophie_contemporaine_de_la_technique:
    output: true
    permalink: /:collection/:path/
    title: "Philosophie contemporaine de la technique : quelques traductions de textes anglais"
    sort_by: title
  l_education_rend_elle_libre:
    output: true
    permalink: /:collection/:path/
    title: "L'éducation rend-elle libre ?"
    sort_by: title
  identite_personnelle:
    output: true
    permalink: /:collection/:path/
    title: "L'identité personnelle"
    sort_by: title
  philosophie_de_la_culture:
    output: true
    permalink: /:collection/:path/
    title: "Philosophie de la culture"
    sort_by: title
  anarchisme:
    output: true
    permalink: /:collection/:path/
    title: "L'anarchisme"
    sort_by: title
  le_bonheur_n_est_il_qu_un_ideal:
    output: true
    permalink: /:collection/:path/
    title: "Le bonheur n'est-il qu'un idéal ?"
    sort_by: title

main:
  - title: "Collections"
    url: /collection-archive/
